services:
  - type: web
    name: smartbuy-dashboard-api
    env: python
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements-render.txt
    startCommand: PYTHONPATH=/opt/render/project/src/backend python backend/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: MONGODB_CONNECTION_STRING
        sync: false
      - key: MONGODB_DATABASE_NAME
        value: ctd

  - type: web
    name: smartbuy-dashboard-frontend
    env: static
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: frontend/dist
    # Add headers to support SPA routing
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
    envVars:
      - key: VITE_API_URL
        value: https://smartbuy-dashboard-api.onrender.com